### ISSUE TITLE
Losing cellular network connection

### ISSUE THREAD

**Issue by janipewter** [BT-P1C0/BT-Hardware#8]
Hi, if this loses the cellular connection because it goes outside network coverage area, will it automatically reconnect when it is back inside the coverage?

**Comment by mglsj** [comment]
I have implemented a basic failed attempts counter for the time being. A proper solution would be checking for response 600s and checking signal strengths. https://stackoverflow.com/questions/15975051/error-httpaction0-601-0/23574960#23574960
